version: '3'

services:
  drf:
    build: .
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    container_name: crud_api
    volumes:
      - .:/crud_api
    ports:
      - "8000:8000"
